version: 2


sources:
  - name: newsanalytics  # This is the source name that you'll use to refer to this project + dataset in dbt
    database: newsanalytics-440610  # Your BigQuery project ID
    schema: testnews1  # Your BigQuery dataset name
    tables:
      - name: DimArticleContent  # This is the name of the table in BigQuery
        description: "Source table containing article content data"
      - name: DimArticleTitle
        description: "Source table containing article titles"
      - name: DimArticleDescription
        description: "Source table containing article descriptions"
      - name: DimArticle
        description: "Source table containing article metadata"
        columns:
          - name: article_id
            description: "Primary key for articles"
            tests:
              - unique
              - not_null
          - name: article_title_id
            description: "Foreign key referencing article title"
          - name: article_description_id
            description: "Foreign key referencing article description"
          - name: article_content_id
            description: "Foreign key referencing article content"
          - name: article_urlToImage
            description: "URL to the main image of the article"
          - name: article_publishedAt
            description: "Publication date and time of the article"
        
      - name: FactNews
        description: "Fact table containing news article metadata"
        columns:
          - name: article_id
            description: "Foreign key referencing article in DimArticle"
            tests:
              - relationships:
                  to: ref('DimArticle')  # This references the DimArticle model in dbt
                  field: article_id
            


models:
  - name: fact_news
    description: "Fact table containing news article metadata."
    columns:
      - name: article_id
        description: "Primary key for articles."
        tests:
          - unique
          - not_null
      - name: source_id
        description: "Source identifier."
      - name: source_name
        description: "Name of the news source."
      - name: author_name
        description: "Author of the article."

  - name: title
    description: "Dimension table containing article titles."
    columns:
      - name: article_title_id
        description: "Primary key for the article title."
        tests:
          - unique
          - not_null
      - name: article_title
        description: "Title of the article."
      - name: pos_count
        description: "JSON object containing part-of-speech counts in the article title."

  - name: desc
    description: "Dimension table containing article descriptions."
    columns:
      - name: article_description_id
        description: "Primary key for the article description."
        tests:
          - unique
          - not_null
      - name: article_description
        description: "Description of the article."
      - name: pos_count
        description: "JSON object containing part-of-speech counts in the article description."

  - name: content
    description: "Dimension table containing article contents."
    columns:
      - name: article_content_id
        description: "Primary key for the article content."
        tests:
          - unique
          - not_null
      - name: article_content
        description: "Content of the article."
      - name: pos_count
        description: "JSON object containing part-of-speech counts in the article content."
